modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "jaom"
version = "${version}"
displayName = "Just Another Ore Mod"
authors = "Ru_Kira, Keeper317, Scyu_"
description = '''
This is a mod for Just Another Mod Pack
'''
#logoFile = ""

[[dependencies.jaom]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.jaom]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.jaom]]
modId = "architectury"
mandatory = true
versionRange = "[6.2.43,)"
ordering = "AFTER"
side = "BOTH"